"""rm_models

Revision ID: ab6bf4578a8f
Revises: d0e0422c9ae6
Create Date: 2026-06-11 08:44:13.054037

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'ab6bf4578a8f'
down_revision: Union[str, None] = 'd0e0422c9ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
