"""rm_models

Revision ID: d0e0422c9ae6
Revises: a57701a8c76e
Create Date: 2026-06-11 08:39:42.376069

"""
from typing import Sequence, Union

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd0e0422c9ae6'
down_revision: Union[str, None] = 'a57701a8c76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_party_post_comment_post_id'), table_name='party_post_comment')
    op.drop_index(op.f('ix_party_post_comment_user_id'), table_name='party_post_comment')
    op.drop_table('party_post_comment')
    op.drop_index(op.f('ix_party_posts_game_id'), table_name='party_posts')
    op.drop_index(op.f('ix_party_posts_user_id'), table_name='party_posts')
    op.drop_table('party_posts')
    op.drop_index(op.f('ix_game_reviews_game_id'), table_name='game_reviews')
    op.drop_index(op.f('ix_game_reviews_user_id'), table_name='game_reviews')
    op.drop_table('game_reviews')
    op.alter_column('games', 'trait_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=6),
               server_default=None,
               existing_nullable=False)
    op.alter_column('games', 'discount_percent',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'discount_percent',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('games', 'trait_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=6),
               server_default=sa.text("'[0,0,0,0,0,0]'::vector"),
               existing_nullable=False)
    op.create_table('party_post_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('representative_stat_tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'deleted', name='party_post_comment_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['party_posts.id'], name=op.f('fk_party_post_comment_post_id_party_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_party_post_comment_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_post_comment'))
    )
    op.create_index(op.f('ix_party_post_comment_user_id'), 'party_post_comment', ['user_id'], unique=False)
    op.create_index(op.f('ix_party_post_comment_post_id'), 'party_post_comment', ['post_id'], unique=False)
    op.create_table('game_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_recommended', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'deleted', name='game_review_status'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_reviews_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_reviews')),
    sa.UniqueConstraint('user_id', 'game_id', name=op.f('uq_game_reviews_user_game'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_game_reviews_user_id'), 'game_reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_game_reviews_game_id'), 'game_reviews', ['game_id'], unique=False)
    op.create_table('party_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('schedule', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('representative_stat_tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_party_posts_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_party_posts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_posts'))
    )
    op.create_index(op.f('ix_party_posts_user_id'), 'party_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_party_posts_game_id'), 'party_posts', ['game_id'], unique=False)
    # ### end Alembic commands ###
