"""update game and recommendation models

Revision ID: bfec882c946c
Revises: f02b0c085ce8
Create Date: 2026-06-08 01:53:44.091321

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision: str = 'bfec882c946c'
down_revision: Union[str, None] = 'f02b0c085ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    recommendation_source_type = postgresql.ENUM(
        'ONLY_SURVEY',
        'HYBRID_STEAM',
        name='recommendation_source_type',
        create_type=False,
    )
    recommendation_source_type.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'recommendation_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_stats_id', sa.Integer(), nullable=False),
        sa.Column('source_type', recommendation_source_type, nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('similarity_score', sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column('similarity_rank', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_recommendation_items_game_id_games'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_items_user_id_users'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], name=op.f('fk_recommendation_items_user_stats_id_user_stats'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_items')),
    )
    op.create_index(op.f('ix_recommendation_items_game_id'), 'recommendation_items', ['game_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_user_id'), 'recommendation_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendation_items_user_stats_id'), 'recommendation_items', ['user_stats_id'], unique=False)

    op.drop_constraint(
        op.f('fk_recommendation_feedbacks_recommendation_id_recommendations'),
        'recommendation_feedbacks',
        type_='foreignkey',
    )

    op.drop_index(op.f('ix_recommendation_audits_run_id'), table_name='recommendation_audits')
    op.drop_index(op.f('ix_recommendation_audits_user_id'), table_name='recommendation_audits')
    op.drop_table('recommendation_audits')

    op.drop_index(op.f('ix_recommendations_game_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_user_stats_id'), table_name='recommendations')
    op.drop_table('recommendations')

    op.drop_index(op.f('ix_game_tags_game_id'), table_name='game_tags')
    op.drop_index(op.f('ix_game_tags_tag_name'), table_name='game_tags')
    op.drop_table('game_tags')

    op.drop_index(op.f('ix_rag_documents_game_id'), table_name='rag_documents')
    op.drop_table('rag_documents')

    op.add_column(
        'games',
        sa.Column(
            'trait_vector',
            Vector(6),
            nullable=False,
            server_default=sa.text("'[0,0,0,0,0,0]'"),
        ),
    )
    op.add_column('games', sa.Column('release_date', sa.Date(), nullable=True))
    op.drop_column('games', 'original_price_krw')
    op.drop_column('games', 'last_synced_at')
    op.drop_column('games', 'discount_percent')

    op.alter_column(
        'party_posts',
        'schedule',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.String(length=200),
        existing_nullable=True,
    )

    op.create_foreign_key(
        op.f('fk_recommendation_feedbacks_recommendation_id_recommendation_items'),
        'recommendation_feedbacks',
        'recommendation_items',
        ['recommendation_id'],
        ['id'],
        ondelete='CASCADE',
    )

    op.add_column('user_stats', sa.Column('primary_tag', sa.String(length=50), nullable=True))
    op.drop_column('user_stats', 'primary_tag_2')
    op.drop_column('user_stats', 'primary_tag_1')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('primary_tag_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_stats', sa.Column('primary_tag_2', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user_stats', 'primary_tag')
    op.drop_constraint(op.f('fk_recommendation_feedbacks_recommendation_id_recommendation_items'), 'recommendation_feedbacks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recommendation_feedbacks_recommendation_id_recommendations'), 'recommendation_feedbacks', 'recommendations', ['recommendation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('party_posts', 'schedule',
               existing_type=sa.String(length=200),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.add_column('games', sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('original_price_krw', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games', 'release_date')
    op.drop_column('games', 'trait_vector')
    op.create_table('recommendation_audits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_type', postgresql.ENUM('ONLY_SURVEY', 'HYBRID_STEAM', name='recommendation_audit_source_type'), autoincrement=False, nullable=False),
    sa.Column('snapshot_combat', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_strategy', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_cooperation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_exploration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_growth', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('snapshot_healing', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('excluded_game_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('override_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recommendations.id'], name=op.f('fk_recommendation_audits_run_id_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_audits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_audits'))
    )
    op.create_index(op.f('ix_recommendation_audits_user_id'), 'recommendation_audits', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendation_audits_run_id'), 'recommendation_audits', ['run_id'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doc_type', postgresql.ENUM('game_wiki', 'genre_guide', 'tag_desc', 'persona', 'recommendation_rule', 'general', name='rag_document_type'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence_status', postgresql.ENUM('reviewed', 'generated', 'deprecated', name='rag_evidence_status'), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('vector_namespace', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vector_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_rag_documents_game_id_games'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_documents'))
    )
    op.create_index(op.f('ix_rag_documents_game_id'), 'rag_documents', ['game_id'], unique=False)
    op.create_table('game_tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('combat_weight', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('strategy_weight', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('cooperation_weight', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('exploration_weight', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('growth_weight', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('healing_weight', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_negative_trigger', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_tags_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_tags'))
    )
    op.create_index(op.f('ix_game_tags_tag_name'), 'game_tags', ['tag_name'], unique=False)
    op.create_index(op.f('ix_game_tags_game_id'), 'game_tags', ['game_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_stats_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('ONLY_SURVEY', 'HYBRID_STEAM', name='recommendation_source_type'), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('match_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('recommendation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_warning', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('warning_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('conflicting_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_recommendations_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], name=op.f('fk_recommendations_user_stats_id_user_stats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_user_stats_id'), 'recommendations', ['user_stats_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_game_id'), 'recommendations', ['game_id'], unique=False)
    op.drop_index(op.f('ix_recommendation_items_user_stats_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_user_id'), table_name='recommendation_items')
    op.drop_index(op.f('ix_recommendation_items_game_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    # ### end Alembic commands ###
