"""create domain models

Revision ID: f02b0c085ce8
Revises: 
Create Date: 2026-06-01 04:28:32.302802

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'f02b0c085ce8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('price_krw', sa.Integer(), nullable=True),
    sa.Column('review_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('steam_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_price_krw', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('is_korean_supported', sa.Boolean(), nullable=False),
    sa.Column('current_players', sa.Integer(), nullable=True),
    sa.Column('current_players_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steam_detail_json', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_app_id'), 'games', ['app_id'], unique=True)
    op.create_table('survey_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('stat_axis', sa.Enum('combat', 'strategy', 'cooperation', 'exploration', 'growth', 'healing', name='stat_axis'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_survey_questions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('bio', sa.String(length=160), nullable=True),
    sa.Column('login_provider', sa.Enum('email', 'steam', name='login_provider'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'withdrawn', 'deleted', name='user_status'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hard_delete_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hard_delete_after'), 'users', ['hard_delete_after'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('SIGNUP', 'PASSWORD_RESET', name='email_verification_purpose'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', name='email_verification_status'), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verifications')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verifications_token_hash'))
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_table('game_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted', name='game_review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_reviews_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_reviews')),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_game_reviews_user_game')
    )
    op.create_index(op.f('ix_game_reviews_game_id'), 'game_reviews', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_reviews_user_id'), 'game_reviews', ['user_id'], unique=False)
    op.create_table('game_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('combat_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('strategy_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('cooperation_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('exploration_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('growth_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('healing_weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('is_negative_trigger', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_tags_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_tags'))
    )
    op.create_index(op.f('ix_game_tags_game_id'), 'game_tags', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_tags_tag_name'), 'game_tags', ['tag_name'], unique=False)
    op.create_table('party_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('schedule', sa.DateTime(timezone=True), nullable=True),
    sa.Column('representative_stat_tag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_party_posts_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_party_posts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_posts'))
    )
    op.create_index(op.f('ix_party_posts_game_id'), 'party_posts', ['game_id'], unique=False)
    op.create_index(op.f('ix_party_posts_user_id'), 'party_posts', ['user_id'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.Enum('game_wiki', 'genre_guide', 'tag_desc', 'persona', 'recommendation_rule', 'general', name='rag_document_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('evidence_status', sa.Enum('reviewed', 'generated', 'deprecated', name='rag_evidence_status'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('vector_namespace', sa.String(length=100), nullable=False),
    sa.Column('vector_id', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_rag_documents_game_id_games'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_documents'))
    )
    op.create_index(op.f('ix_rag_documents_game_id'), 'rag_documents', ['game_id'], unique=False)
    op.create_table('steam_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('steam_id_64', sa.BigInteger(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('steam_sync_status', sa.Enum('success', 'private', 'failed', 'empty', name='steam_sync_status'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_steam_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steam_accounts')),
    sa.UniqueConstraint('user_id', name='uq_steam_accounts_user_id')
    )
    op.create_index(op.f('ix_steam_accounts_steam_id_64'), 'steam_accounts', ['steam_id_64'], unique=True)
    op.create_index(op.f('ix_steam_accounts_user_id'), 'steam_accounts', ['user_id'], unique=False)
    op.create_table('user_library_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('steam_app_id', sa.BigInteger(), nullable=False),
    sa.Column('playtime_minutes', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_library_games_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_library_games')),
    sa.UniqueConstraint('user_id', 'steam_app_id', name='uq_user_library_games_user_app')
    )
    op.create_index(op.f('ix_user_library_games_steam_app_id'), 'user_library_games', ['steam_app_id'], unique=False)
    op.create_index(op.f('ix_user_library_games_user_id'), 'user_library_games', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('combat', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.Integer(), nullable=False),
    sa.Column('cooperation', sa.Integer(), nullable=False),
    sa.Column('exploration', sa.Integer(), nullable=False),
    sa.Column('growth', sa.Integer(), nullable=False),
    sa.Column('healing', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ONLY_SURVEY', 'HYBRID_STEAM', name='stat_source_type'), nullable=False),
    sa.Column('survey_mode', sa.Enum('standard', 'chatbot', name='survey_mode'), nullable=True),
    sa.Column('negative_tags', sa.JSON(), nullable=False),
    sa.Column('primary_tag_1', sa.String(length=50), nullable=True),
    sa.Column('primary_tag_2', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_stats'))
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=False)
    op.create_table('user_withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CANCELLED', 'HARD_DELETED', name='user_withdrawal_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hard_delete_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hard_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_withdrawal_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_withdrawal_requests'))
    )
    op.create_index(op.f('ix_user_withdrawal_requests_hard_delete_after'), 'user_withdrawal_requests', ['hard_delete_after'], unique=False)
    op.create_index(op.f('ix_user_withdrawal_requests_status'), 'user_withdrawal_requests', ['status'], unique=False)
    op.create_index(op.f('ix_user_withdrawal_requests_user_id'), 'user_withdrawal_requests', ['user_id'], unique=False)
    op.create_table('party_post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('representative_stat_tag', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'deleted', name='party_post_comment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['party_posts.id'], name=op.f('fk_party_post_comment_post_id_party_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_party_post_comment_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_post_comment'))
    )
    op.create_index(op.f('ix_party_post_comment_post_id'), 'party_post_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_party_post_comment_user_id'), 'party_post_comment', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('ONLY_SURVEY', 'HYBRID_STEAM', name='recommendation_source_type'), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('is_warning', sa.Boolean(), nullable=False),
    sa.Column('warning_reason', sa.Text(), nullable=True),
    sa.Column('conflicting_tags', sa.JSON(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_recommendations_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], name=op.f('fk_recommendations_user_stats_id_user_stats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_game_id'), 'recommendations', ['game_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_stats_id'), 'recommendations', ['user_stats_id'], unique=False)
    op.create_table('recommendation_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('ONLY_SURVEY', 'HYBRID_STEAM', name='recommendation_audit_source_type'), nullable=False),
    sa.Column('snapshot_combat', sa.Integer(), nullable=False),
    sa.Column('snapshot_strategy', sa.Integer(), nullable=False),
    sa.Column('snapshot_cooperation', sa.Integer(), nullable=False),
    sa.Column('snapshot_exploration', sa.Integer(), nullable=False),
    sa.Column('snapshot_growth', sa.Integer(), nullable=False),
    sa.Column('snapshot_healing', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('excluded_game_ids', sa.JSON(), nullable=False),
    sa.Column('override_filters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['recommendations.id'], name=op.f('fk_recommendation_audits_run_id_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_audits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_audits'))
    )
    op.create_index(op.f('ix_recommendation_audits_run_id'), 'recommendation_audits', ['run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_audits_user_id'), 'recommendation_audits', ['user_id'], unique=False)
    op.create_table('recommendation_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.Enum('like', 'wishlist', 'not_interested', name='recommendation_feedback_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_recommendation_feedbacks_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_feedbacks_recommendation_id_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_feedbacks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_feedbacks'))
    )
    op.create_index(op.f('ix_recommendation_feedbacks_game_id'), 'recommendation_feedbacks', ['game_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedbacks_recommendation_id'), 'recommendation_feedbacks', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedbacks_user_id'), 'recommendation_feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedbacks_user_id'), table_name='recommendation_feedbacks')
    op.drop_index(op.f('ix_recommendation_feedbacks_recommendation_id'), table_name='recommendation_feedbacks')
    op.drop_index(op.f('ix_recommendation_feedbacks_game_id'), table_name='recommendation_feedbacks')
    op.drop_table('recommendation_feedbacks')
    op.drop_index(op.f('ix_recommendation_audits_user_id'), table_name='recommendation_audits')
    op.drop_index(op.f('ix_recommendation_audits_run_id'), table_name='recommendation_audits')
    op.drop_table('recommendation_audits')
    op.drop_index(op.f('ix_recommendations_user_stats_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_game_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_party_post_comment_user_id'), table_name='party_post_comment')
    op.drop_index(op.f('ix_party_post_comment_post_id'), table_name='party_post_comment')
    op.drop_table('party_post_comment')
    op.drop_index(op.f('ix_user_withdrawal_requests_user_id'), table_name='user_withdrawal_requests')
    op.drop_index(op.f('ix_user_withdrawal_requests_status'), table_name='user_withdrawal_requests')
    op.drop_index(op.f('ix_user_withdrawal_requests_hard_delete_after'), table_name='user_withdrawal_requests')
    op.drop_table('user_withdrawal_requests')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_library_games_user_id'), table_name='user_library_games')
    op.drop_index(op.f('ix_user_library_games_steam_app_id'), table_name='user_library_games')
    op.drop_table('user_library_games')
    op.drop_index(op.f('ix_steam_accounts_user_id'), table_name='steam_accounts')
    op.drop_index(op.f('ix_steam_accounts_steam_id_64'), table_name='steam_accounts')
    op.drop_table('steam_accounts')
    op.drop_index(op.f('ix_rag_documents_game_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('ix_party_posts_user_id'), table_name='party_posts')
    op.drop_index(op.f('ix_party_posts_game_id'), table_name='party_posts')
    op.drop_table('party_posts')
    op.drop_index(op.f('ix_game_tags_tag_name'), table_name='game_tags')
    op.drop_index(op.f('ix_game_tags_game_id'), table_name='game_tags')
    op.drop_table('game_tags')
    op.drop_index(op.f('ix_game_reviews_user_id'), table_name='game_reviews')
    op.drop_index(op.f('ix_game_reviews_game_id'), table_name='game_reviews')
    op.drop_table('game_reviews')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_hard_delete_after'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('survey_questions')
    op.drop_index(op.f('ix_games_app_id'), table_name='games')
    op.drop_table('games')
    op.execute('DROP TYPE IF EXISTS recommendation_feedback_type')
    op.execute('DROP TYPE IF EXISTS recommendation_audit_source_type')
    op.execute('DROP TYPE IF EXISTS recommendation_source_type')
    op.execute('DROP TYPE IF EXISTS party_post_comment_status')
    op.execute('DROP TYPE IF EXISTS user_withdrawal_status')
    op.execute('DROP TYPE IF EXISTS survey_mode')
    op.execute('DROP TYPE IF EXISTS stat_source_type')
    op.execute('DROP TYPE IF EXISTS steam_sync_status')
    op.execute('DROP TYPE IF EXISTS rag_evidence_status')
    op.execute('DROP TYPE IF EXISTS rag_document_type')
    op.execute('DROP TYPE IF EXISTS game_review_status')
    op.execute('DROP TYPE IF EXISTS email_verification_status')
    op.execute('DROP TYPE IF EXISTS email_verification_purpose')
    op.execute('DROP TYPE IF EXISTS gender')
    op.execute('DROP TYPE IF EXISTS user_status')
    op.execute('DROP TYPE IF EXISTS login_provider')
    op.execute('DROP TYPE IF EXISTS stat_axis')
    # ### end Alembic commands ###
