name: Prod Deploy

on:
  push:
    branches: [main]

jobs:
  prod_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Actions IP 조회
        id: ip
        uses: haythem/public-ip@v1.3

      - name: AWS 자격증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Security Group에 IP 추가
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: EC2 SSH 배포
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USER }}
          key: ${{ secrets.EC2_DEV_SSH_KEY }}
          script: |
            cd ~/gembti_BE
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker image prune -af

      - name: Security Group에서 IP 제거
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32 \
            --region ap-northeast-2
